ENV_SPACES_KEY                  = "ENV_SPACES_KEY"

SERVER_POLICY_PARAMS_KEY        = "SERVER_POLICY_PARAMS_KEY"
SERVER_STRATEGY_FRAMES_KEY      = "SERVER_STRATEGY_FRAMES_KEY"
SERVER_STRATEGY_HISTORY_KEY     = "SERVER_STRATEGY_HISTORY_KEY"
SERVER_VAL_PARAMS_KEY           = "SERVER_VAL_PARAMS_KEY"
SERVER_CURRENT_UPDATE_KEY       = "SERVER_CURRENT_UPDATE_KEY"
SERVER_CUMULATIVE_TIMESTEPS_KEY = "SERVER_CUMULATIVE_TIMESTEPS_KEY"
SERVER_CURRENT_STATUS_KEY       = "SERVER_CURRENT_STATUS_KEY"
SERVER_CONFIG_KEY               = "SERVER_CONFIG_KEY"

CLIENT_POLICY_REWARD_KEY        = "CLIENT_POLICY_REWARD_KEY"
CLIENT_POLICY_GRADIENT_KEY      = "CLIENT_POLICY_GRADIENT_KEY"
CLIENT_VALUE_GRADIENT_KEY       = "CLIENT_VALUE_GRADIENT_KEY"
CLIENT_NOVELTY_GRADIENT_KEY     = "CLIENT_NOVELTY_GRADIENT_KEY"
CLIENT_EXPERIENCE_KEY           = "CLIENT_EXPERIENCE_KEY"

RUNNING_REWARD_MEAN_KEY         = "RUNNING_REWARD_MEAN_KEY"
RUNNING_REWARD_STD_KEY          = "RUNNING_REWARD_STD_KEY"

NEW_DATA_AMOUNT_KEY             = "NEW_DATA_AMOUNT_KEY"

MARL_CURRENT_OPPONENT_KEY       = "MARL_CURRENT_OPPONENT_KEY"
MARL_MATCH_RESULTS_KEY          = "MARL_MATCH_RESULTS_KEY"

MEAN_POLICY_REWARD_KEY          = "MEAN_POLICY_REWARD_KEY"
